### ISSUE TITLE
cdn.bootcss屏蔽了部分网址后缀js需要本地化

### ISSUE THREAD

**Issue by findwisdom** [helloxz/imgurl#11]
https://imgurl.org/temp/1805/bda4401f9c359a84.jpg

**Comment by helloxz** [comment]
这个坑爹了，感谢您的提醒，有空我更新下资源调用。

**Comment by helloxz** [comment]
您好，最新的2.x版本，全部改为本地资源调用。可参考[帮助文档](https://doc.xiaoz.me/#/imgurl2/upgrade) 进行升级。
