### ISSUE TITLE
出现错误：目标文件目录不能被创建，不能进行处理

### ISSUE THREAD

**Issue by mixool** [helloxz/imgurl#12]
使用的lamp一键搭建好环境。
下载master.zip解压后已经修改这2处：
define("APP","/data/www/img.slier.net/");
"domain"    =>  "https://img.slier.net/",

**Comment by helloxz** [comment]
请尝试执行`chown -R www:www /data/www/img.slier.net/`然后再试一下。

**Comment by helloxz** [comment]
1. `ls -al`看下站点目录是不是有`.user.ini`这个文件，如果有参考：https://blog.csdn.net/song_csdn1550/article/details/52191579 进行删除。
2. 检查站点目录下是否存在`temp`目录，如果不存在请创建并赋予777权限。（`chmod 777 temp`）

**Comment by mixool** [comment]
解决了，原来是lamp那边的常见错误，一根筋的以为是这边..
Q1：安装完网站程序，升级或安装插件等报错，如何更改网站目录权限？
以 root 登录后，运行：chown -R apache:apache /data/www/域名/
