### ISSUE TITLE
一定程度缩小浏览器窗口后首页导航栏显示两个”探索发现“按钮

### ISSUE THREAD

**Issue by xirikm** [helloxz/imgurl#20]
浏览器全屏的话显示是正常的，但在一定程度的缩小浏览器窗口后顶部出现了两个”探索发现“按钮，如下图：

![](https://imgurl.org/temp/1810/8c5f35e1073e6779.jpg)

检查了一下代码，问题出在 ./tpl/user/header.php 里如下图的部分

![](https://imgurl.org/temp/1810/043d081ad11e4d62.jpg)

没有读完你的所有代码，但感觉这部分完全是多余的，望解决

**Comment by helloxz** [comment]
最新版的代码已经解决这个问题，请参考帮助文档进行升级即可。
