### ISSUE TITLE
有没有计划支持backblaze？并且支持设定链接域名

### ISSUE THREAD

**Issue by zhanggaoxuan** [helloxz/imgurl#22]
https://www.backblaze.com/blog/backblaze-and-cloudflare-partner-to-provide-free-data-transfer/
存储便宜。流量还不要钱

**Comment by helloxz** [comment]
谢谢，我先查看一下。

**Comment by helloxz** [comment]
您好，专业版已经支持BackBlaze B2，如有兴趣可查看：[https://www.xiaoz.me/archives/13225](ImgURL Pro专业版发布，支持多个外部存储)
