### ISSUE TITLE
使用 Nginx 作为服务器，启动安装提示目录不可写，组件不支持等

### ISSUE THREAD

**Issue by woshijpf** [helloxz/imgurl#23]
![image](https://user-images.githubusercontent.com/8475378/48566119-028af600-e935-11e8-94cb-0b0946af6d1f.png)
安装启动运行之后出现上面图中的错误信息，不知道是什么原因：

master.zip 中的内容解压到 /home/www 目录中

nginx的默认配置中只修改了下面的内容如下：
```bash
location / {
            root   /home/www;
            index  index.php index.html;
        }

        location ~ \.php$ {
           root           /home/www;
           fastcgi_pass   127.0.0.1:9000;          #php-fpm的地址
           fastcgi_index  index.php;
           include        fastcgi.conf;
        }
```

**Comment by helloxz** [comment]
1. 不可写的问题，请检查您/home/www 目录权限，对应的用户必须可写
2. 您的php是直接`yum`安装的？PHP需要支持pdo_sqlite组件，您可以通过`phpinfo()`来查看，若没有该组件，需要重新编译PHP

**Comment by woshijpf** [comment]
@helloxz  多谢了~的确是因为我使用的是 yum 直接安装的 php 的问题

**Comment by woshijpf** [comment]
![image](https://user-images.githubusercontent.com/8475378/48788983-eddca280-ed26-11e8-9b86-26f4fcaa1075.png)
MWEB 中自定义图床功能各个选线的含义参考：https://zh.mweb.im/mweb-1.9.1-release.html
无奈我是个前端盲，不知道这个该怎么配置了，想请教一下大神 @helloxz

**Comment by woshijpf** [comment]
根据 Mweb 软件的报错信息定位到问题是出现在 Mweb 的Post请求头只支持`content-type:application/json`格式的，而在源码 `functions/api.php` 中 header 为 `header('Access-Control-Allow-Origin:*')`，所以只要将 `Access-Control-Allow-Origin:*`替换成 `content-type:application/json`就可以了。
