### ISSUE TITLE
ctrl + v 上传返回 500

### ISSUE THREAD

**Issue by kbrx93** [helloxz/imgurl#26]
如题，选取上传正常

**Comment by helloxz** [comment]
在`php.ini`中开启详细报错，然后重启一次web或php-fpm，然后F12控制台看下具体报什么错误。需要协助可添加我QQ：337003006

**Comment by kbrx93** [comment]
嗯，不过文档里也没说，像我这种对 PHP 不熟的人就比较头疼，得花点时间找问题。
最好在文档里提及下。

**Comment by helloxz** [comment]
好的，感谢反馈。问题解决没有？

**Comment by kbrx93** [comment]
OK了，自己改写了下就好了，主要是 PHP 不熟悉。

**Comment by kbrx93** [comment]
再提个建议，就是重构的时候能把文件大小限制的功能放到后台管理面板中或者配置文件中比较好，毕竟针对的是自用的人，这样更友好些，虽然直接改代码也不难，但总有可能出现这样或那样的错误。

**Comment by helloxz** [comment]
嗯，这个在计划中，重构后的都是通过后台直接设置各种参数，不用再直接改配置文件。
