### ISSUE TITLE
无法在后台管理图片

### ISSUE THREAD

**Issue by johnpoint** [helloxz/imgurl#3]
进入后台后所有功能都用不了

**Comment by johnpoint** [comment]
![](https://tc.lvcshu.com/upload/1803/2b64a4c48835d3b1.png)
如图，实际上是已经有图片的

**Comment by helloxz** [comment]
您好，请问进入的是https://domain.com/admin/ 这个后台地址吗？

**Comment by johnpoint** [comment]
是的

**Comment by johnpoint** [comment]
https://tc.lvcshu.com/admin/pics.php?type=admin
这样子

**Comment by helloxz** [comment]
检查 data/imgurl.db3 数据库是否拥有写权限

**Comment by johnpoint** [comment]
`chmod 777`
了，仍然无法显示，附图
![](https://tc.lvcshu.com/upload/1803/a2e60cd7d08e4728.png)

**Comment by helloxz** [comment]
今天更新了新版本，用新版本的试试呢。

**Comment by johnpoint** [comment]
还是不行
orz
大佬可以说说文件夹内的权限设定吗？
除此之外没什么问题

**Comment by helloxz** [comment]
你是windows还是linux系统？db/temp/upload目录需要可写。

**Comment by johnpoint** [comment]
我把数据库权限设为777，可以了，谢谢大佬的改写，好看了很多呢！
