### ISSUE TITLE
The requested URL /install/ was not found on this server.

### ISSUE THREAD

**Issue by zwenke** [helloxz/imgurl#31]

**Comment by helloxz** [comment]
参考下：![](https://doc.xiaoz.me/#/imgurl2/install) 检查下伪静态设置

**Comment by zwenke** [comment]
Apache 配置不对。
将文档目录下的
` Options FollowSymLinks AllowOverride None` 
改为
`Options FollowSymLinks AllowOverride All`
后就可以了。

感谢答疑。

**Comment by helloxz** [comment]
好的，问题解决了就好。
