### ISSUE TITLE
怎么安装ImageMagick

### ISSUE THREAD

**Issue by Leozhu123** [helloxz/imgurl#32]
RT

**Comment by helloxz** [comment]
阁下使用的是一键包还是自己搭建的环境呢？如果使用的宝塔面板可以参考：[宝塔面板安装ImgURL图床](https://www.xiaoz.me/archives/12081)

**Comment by Leozhu123** [comment]
系统ubuntu18.04 已apt install imagemagick 但还是显示未安装

**Comment by IoTgod** [comment]
还需要安装PHP Imagick扩展

**Comment by helloxz** [comment]
您好，最新版不再强制要求ImageMagick，请访问：[https://github.com/helloxz/imgurl/releases](https://github.com/helloxz/imgurl/releases) 进行下载。
