### ISSUE TITLE
希望能增加七牛图床

### ISSUE THREAD

**Issue by liujiachao** [helloxz/imgurl#33]
因为服务器部署在美国，国内访问还是慢了一点，希望imgurl能增加七牛图床功能

再次感谢作者的图床作品，很好用。

**Comment by xiebruce** [comment]
我的[PicUploader](https://github.com/xiebruce/PicUploader)支持七牛，不过需要稍作配置，目前支持的图床有：七牛、阿里、腾讯、网易、京东、百度、又拍、青云、Ucloud、sm.ms、Imgur、Gibhub、微博、Nextcloud、个人服务器(sftp)，有兴趣可以看看。

**Comment by helloxz** [comment]
您好，社区版可能不会增加外部图床，Pro版已经支持七牛：[https://www.xiaoz.me/archives/13225](https://www.xiaoz.me/archives/13225)，感谢支持。
