### ISSUE TITLE
win10中部署成功，但是出现一个小问题

### ISSUE THREAD

**Issue by yousifun** [helloxz/imgurl#43]
进入首页出现以下问题，但是不影响使用。PHP 5.6  nginx 1.12
```
A PHP Error was encountered
Severity: Core Warning
Message: PHP Startup:
Filename: Unknown
Line Number: 0
Backtrace:
```

![](https://ww1.sinaimg.cn/large/006Fzy5igy1g29flvfi7lj31cl0mb7wh.jpg)

**Comment by helloxz** [comment]
PHP版本多少的呀？建议5.6以上

**Comment by yousifun** [comment]
php-nts-5.6.9

问题已经解决了，是php_imagick的问题，我用的PHP版本是php-nts-5.6.9，开始我用的是php_imagick-3.4.3rc1-5.6-ts-vc11-x86，这个是线程安全的；需要更换版本为php_imagick-3.4.3rc1-5.6-nts-vc11-x86非线程安全的。和PHP版本的冲突。

**Comment by helloxz** [comment]
好的，最新版不强制要求imagick，去掉这个扩展将下滑到GD2，也能正常使用。
