### ISSUE TITLE
caddy的伪静态有没有？

### ISSUE THREAD

**Issue by petcat** [helloxz/imgurl#44]
现在就缺了 caddy 的 rewrite 了

**Comment by helloxz** [comment]
Google了一下，试试下面的规则有用没有：
```nginx
rewrite {
                to {path} {path}/ /index.php?/{uri}
        }
```

**Comment by petcat** [comment]
谢谢，有用。可以跳转到 install 目录了

**Comment by petcat** [comment]
全是错误，居然忘了装pdo_sqlite，
用debian系就是方便，马上补上
apt-get install php7.0-sqlite
chown -R www-data:www-data /imgurl/*

**Comment by helloxz** [comment]
嗯，问题解决了吗？

**Comment by petcat** [comment]
已解决，建议放上安装文档上面

**Comment by helloxz** [comment]
好的，随后我更新到帮助文档。

**Comment by petcat** [comment]
报告两个bug，不确定是那个关系

1、探索发现页面不显示已上传的图片，虽然我是开了cache，但没道理2个小时仍然不刷新缓存；
2、关于这样独立页面不显示具体内容

**Comment by helloxz** [comment]
1. 探索发现不会显示管理员上传的图片，注意是不是登录后上传的
2. 关于不显示内容是CSS的原因，下载https://github.com/helloxz/imgurl/archive/master.zip 覆盖试一下。

**Comment by petcat** [comment]
晕，果然，非管理员就马上显示图片了

CSS？我是下午才下载安装的啊，还不够最新的？

**Comment by helloxz** [comment]
release不是最新的，master分支才是最新：https://github.com/helloxz/imgurl/archive/master.zip 
或者你可以单独下载拷贝style.css 覆盖，然后`Ctrl + F5`强制刷新。

**Comment by petcat** [comment]
> release不是最新的，master分支才是最新：https://github.com/helloxz/imgurl/archive/master.zip
> 或者你可以单独下载拷贝style.css 覆盖，然后`Ctrl + F5`强制刷新。

测试一天，发现手机端体验好差，尤其是进后台，左边菜单硬生生占了左边一半屏幕，右边一半屏幕显示不知是什么东西。请问这是因为没有做适配，还是又是CSS的问题？

**Comment by helloxz** [comment]
手机端没有怎么做优化，管理图片还是用PC吧，手机端基本的上传和查看没问题。
