### ISSUE TITLE
2.21，没install文件夹，该如何部署。

### ISSUE THREAD

**Issue by ABPolaris** [helloxz/imgurl#45]
git clone了2.21的源码，可是没发现install文件夹。
根据提示“访问您的域名http(s)://domain.com/install/?setup=1”，提示404。
所以2.21版本该如何部署，还是要从旧版本升级？

**Comment by helloxz** [comment]
安装之前建议先参考查看帮助文档： [https://doc.xiaoz.me/#/imgurl2/](https://doc.xiaoz.me/#/imgurl2/)
![](https://i.bmp.ovh/imgs/2019/04/fe824d307782cc80.png)

**Comment by ABPolaris** [comment]
> 安装之前建议先参考查看帮助文档： https://doc.xiaoz.me/#/imgurl2/
> ![](https://camo.githubusercontent.com/b02bd829cd7a663a70a6212bb572c8438b79f730/68747470733a2f2f692e626d702e6f76682f696d67732f323031392f30342f666538323464333037373832636338302e706e67)


我用的Apache，根据文档是不用改什么东西的。
看过之前的issue ，他的方法在我这似乎行不通，还是404。
系统环境是CentOS6。

**Comment by helloxz** [comment]
1. 确认下是否没有使用Apache而是用的nginx
2. 如果确认是Apache，检查下Apache重写模块开启没有呢

**Comment by ABPolaris** [comment]
1.确定是Apache。
2.重写模块应该是开启了（反正httpd.conf里AllowOverride None全改成All了），也在站点根目录建了.htaccess文件，里面写RewriteEngine On 了。

**Comment by ABPolaris** [comment]
试了一下，访问 domain.com/index.php ，会跳转到 domain.com/install/ ，看来重写是正常的。

**Comment by helloxz** [comment]
你访问`http://domain.com/index.php/install/` 试下能打开不。

**Comment by ABPolaris** [comment]
好吧，问题解决了，是我.htaccess文件没写好…
现在写好以后可以正常访问了。

**Comment by helloxz** [comment]
是默认的`.htaccess`没有生效吗？

**Comment by ABPolaris** [comment]
不知道…反正我写好.htaccess后能用了。
