### ISSUE TITLE
密码的正则为什么限制特殊字符？

### ISSUE THREAD

**Issue by vitoland** [helloxz/imgurl#47]
[a-zA-Z0-9!@#$%^&*.]
看了一下密码验证格式，发现只允许几个特殊字符，我常用的 ( ) 不在里面。
一般不都是验证一下位数和复杂度吗，为什么还要做这个限制，反正都是要散列入库的。

**Comment by helloxz** [comment]
哈哈，严谨一点是好事嘛。你可以修改下正则加进去就行了，英文状态下的`( ) `和中文状态的感觉容易混。
