### ISSUE TITLE
请问下有没有支持又拍云作为外部存储的计划

### ISSUE THREAD

**Issue by lePig** [helloxz/imgurl#48]
看了其他的issue，有支持oss的。可能还有七牛的

但是我是又拍云的忠实用户，因为七牛的https要单独收费，没有免费额度，所以一直没用。阿里的oss也取消了免费额度。所以基本上都转到又拍云这边了。

**Comment by xiebruce** [comment]
我的[PicUploader](https://github.com/xiebruce/PicUploader)支持又拍，不过需要稍作配置，有兴趣可以看看。

**Comment by lePig** [comment]
@xiebruce 感谢推荐。 大概看了下 桌面上用 好像挺不错的

**Comment by xiebruce** [comment]
@lePig 对，就是要配置一下，配置好了用起来挺方便的！特别是在Mac下结合Alfred就更方便了，Win当然也可以用。
