### ISSUE TITLE
请问密码忘记了，如何解决

### ISSUE THREAD

**Issue by liujiachao** [helloxz/imgurl#52]
因为自己一时疏忽，密码忘记了，请问如何解决，不考虑重新安装的情况下。

**Comment by helloxz** [comment]
可以参考帮助文档：[https://www.xiaoz.me/doc/doc-imgurl/maintain](https://www.xiaoz.me/doc/doc-imgurl/maintain) 重置密码。

**Comment by liujiachao** [comment]
已解决，感谢指导
