### ISSUE TITLE
希望增加外部存储方案.

### ISSUE THREAD

**Issue by bigcaibao** [helloxz/imgurl#54]
我从很早很早就星了这款程序,一直在期待外部存储方案.
我在你博客上看到你说计划一个月内推出外部存储方案,有希望吗?

**Comment by helloxz** [comment]
您好，ImgURL Pro已经支持多个外部存储，更多说明可参考：[ImgURL Pro专业版发布，支持多个外部存储](https://www.xiaoz.me/archives/13225)
