### ISSUE TITLE
图片压缩请教

### ISSUE THREAD

**Issue by happy3014** [helloxz/imgurl#58]
我自己按照教程搭建了一下，用着很好，非常感谢你的分享。然后我看后台有压缩的功能，请问这个功能具体是怎么使用的呢？什么情况会触发这个压缩呢？如果触发了是不是上传到服务器的就是压缩后的图片，原图不会上传？

**Comment by helloxz** [comment]
图片压缩是在服务端完成的，帮助文档里面有说明，你可以参考下：[https://www.xiaoz.me/doc/doc-imgurl/maintain](https://www.xiaoz.me/doc/doc-imgurl/maintain)

**Comment by happy3014** [comment]
哦哦，谢谢

**Comment by helloxz** [comment]
不客气，这个Issues先关闭了，有问题请再反馈。
