### ISSUE TITLE
关于SSL

### ISSUE THREAD

**Issue by Latezly** [helloxz/imgurl#62]
我对网站本身启动了SSL且强制跳转，但是上传的图片给出的直链还是HTTP，不过手动更改为HTTPS协议的直链也是可以访问的，请问这个是有什么方法可以直接给出HTTPS的图片直链吗

**Comment by helloxz** [comment]
1. 这种情况是因为您在安装的时候是HTTP，HTTP域名已经写入数据库，后来您再去部署了HTTPS，但是数据库里面的域名并不会自动变更。
2. 解决办法是修改`/data/imgurl.db3`找到`storage`表，将里面的HTTP域名修改为HTTPS

**Comment by Latezly** [comment]
感谢回复，已修改成功
