### ISSUE TITLE
多图上传一次性最多上传5张图的限制如何修改

### ISSUE THREAD

**Issue by ShawnQiang1** [helloxz/imgurl#64]
吐槽一下，这个限制没有必要，纯属麻烦人，希望作者能够去掉

**Comment by ShawnQiang1** [comment]
没事了，原来是我修改参数后没重启php，不过建议作者取消掉这个限制

**Comment by helloxz** [comment]
因为ImgURL社区版使用的SQLite数据库，这个数据库并发有限，考虑到稳定性问题，前端限制了多图上传数量。在`embed.js`可修改`number`这个参数。
