### ISSUE TITLE
ftp是否可以添加自定义存储路径

### ISSUE THREAD

**Issue by AishaFisher** [helloxz/imgurl#66]
默认是"/imgs/..." 开始。想要后台自定义添加目录。比如ftp存储路径为"/自定义目录/imgs/..."。然后访问就是"domain/imgs/..."
我在FtpUp.php修改了$datas的path 和$info的url和thumbnail_url相关路径问题。目前使用略缩图和详情页图片显示和url没问题。。就是不知道还有改哪里

**Comment by helloxz** [comment]
您好，改动的地方比较多，暂时不支持自定义路径。
