### ISSUE TITLE
新手安装的v2.31-20190902版本 后台没有看见token管理，应该在哪里设置？

### ISSUE THREAD

**Issue by aruoop** [helloxz/imgurl#69]
新手安装的v2.31-20190902版本 后台没有看见token管理，应该在哪里设置？

**Comment by aruoop** [comment]
还是说社区版本没有api？

**Comment by helloxz** [comment]
您好，社区版支持API：https://www.yuque.com/helloz/imgurl/api
但是不支持token管理。
