### ISSUE TITLE
关于API

### ISSUE THREAD

**Issue by moguv587** [helloxz/imgurl#7]
有没有API开发计划=。=寻思着做插件的话比较方便

**Comment by helloxz** [comment]
有的，API接口正在开发中。

**Comment by helloxz** [comment]
1. v1.3版本已经支持API，请参考帮助文档：[https://doc.xiaoz.me/#/imgurl/api](https://doc.xiaoz.me/#/imgurl/api) 
2. “网站域名和图片外链域名分开”其实很简单，你在主机上同时绑定域名A和B，然后`config.php`设置为B的域名就可以了，这样通过A上传，生成的链接是B的。

**Comment by helloxz** [comment]
现在ImgURL已经更新到2.x了，支持API，域名和图片链接也可以分开了，请参考：[https://doc.xiaoz.me/#/imgurl2/upgrade](https://doc.xiaoz.me/#/imgurl2/upgrade) 进行升级。
