### ISSUE TITLE
安装的时候不用数据库？

### ISSUE THREAD

**Issue by chypay** [helloxz/imgurl#71]
安装的时候不用数据库？
宝塔环境，安装好php扩展，上传好文件，设置了下用户名就行了。
那还要数据库吗？

**Comment by helloxz** [comment]
使用的SQLite3数据库，文件型数据库，不需要额外设置。

**Comment by chypay** [comment]
那我需要在application/config/database.php配置数据库信息吗？

**Comment by helloxz** [comment]
不用，无需修改，默认已经配置好了。
