### ISSUE TITLE
Store Cross Site Script Attack on Upload  HTTP Request Header 

### ISSUE THREAD

**Issue by mcblog** [helloxz/imgurl#72]
Hi,  how is going?  I test imgurl upload functions. And I found a XSS vulnarability.

## First step：

 Put payload on upload header : `X-Forwarded-For: "><img src=# onerror=alert(/a/)>`

![a](https://user-images.githubusercontent.com/30430287/129504791-dceafb9f-e58e-4f3a-82da-87b8790d0d68.png)

![微信截图_20210816093947](https://user-images.githubusercontent.com/30430287/129501918-bb2ca1a0-244b-45c9-8bbe-6d7eb738f8cb.png)

## Second
then web administrator click 

![微信截图_20210816094107](https://user-images.githubusercontent.com/30430287/129501989-60ab6765-8ebf-4e74-a1a1-506f559d2503.png)

![微信截图_20210816094127](https://user-images.githubusercontent.com/30430287/129502002-64c59e3c-d8ea-491c-ac0c-eeb5188ac80d.png)

![微信截图_20210816094207](https://user-images.githubusercontent.com/30430287/129502015-13a6f8ef-fc69-4181-941d-6197025f094a.png)

---
## The method to solve it:
all the request header filter special character。

过滤http请求头的所有特殊字符。

**Comment by helloxz** [comment]
感谢您的反馈，这应该是由于获取用户IP的时候，XFF头没有进行验证导致。我修复一下。
