### ISSUE TITLE
能不能增加个从URL增加链接的功能

### ISSUE THREAD

**Issue by sukara1992** [helloxz/imgurl#8]
![360 16330109415425](https://user-images.githubusercontent.com/30254375/39675324-15b3d9f4-518c-11e8-84c4-087326f03635.jpg)
如图，类似的功能，平时需要下载图片再上传到图床，像这种能省很多时间

**Comment by sukara1992** [comment]
也就是上传远程图片功能，最好能实现从HTML代码中智能提取图片链接进行上传
例如我这一段html
<img src="https://pic.ppccaa.com/087326f03635.jpg" />
[img]https://pic.ppccaa.com/087326f03635.jpg[/img]
程序能过滤出其中图片的地址是
https://pic.ppccaa.com/087326f03635.jpg和https://pic.ppccaa.com/025.jpg
然后下载这两张图片到服务器

**Comment by helloxz** [comment]
1. 从HTML代码中提取图片有点麻烦，而且不排除抓取到不需要的图片，暂时不会考虑。
2. 从单个或多个URL批量上传计划在下个版本中添加

**Comment by helloxz** [comment]
v1.2 已经支持URL批量上传，参考：[帮助文档](https://doc.xiaoz.me/#/imgurl/upgrade?id=v11%E5%8D%87%E7%BA%A7%E4%B8%BAv12) 升级即可。
